Makefile.am

Fixes #2
Signed-off-by: Alexios Zavras <github@zvr.gr>

Leave CFLAGS for user to set up

---

src/main.c
src/tracer.c
src/tracer.h

added storage specifiers to functions in order to depollute the global symbols table and improve performance.

added storage specifiers

---

src/main.c
src/tracer.c

Had forgotten a debugging printf

Remove debugging printf

---

src/tracer.c
src/types.h

openat(2) now handled properly

---

src/record.h

We shouldn't rely on include order, that's a recipe for disaster.

No include order reliance

---

src/record.c
src/record.h

Pass struct pointer instead. More readable.

Use file info instead

---

src/tracer.c

`handle_syscall(3)` is now more organized and easier to extend functionality.

Restructure handle syscall

---

Makefile.am

Add record c in source

---

src/main.c

An initial demo to use for testing the application until #55 is resolved.

output file demo for testing

---

doc/output.md
src/record.c
src/record.h

- Add documentation about and code for environment recording

Environment recording

---

src/main.c
src/tracer.c

now tracks envp using the record functions

---

src/tracer.c
src/types.h

Unique ids

---

src/record.c
src/record.h

- Add recording of command line of processes as a single string

Record command line

---

src/record.c

[BUGFIX] now properly initializes allocated buffer before using strcat

---

src/tracer.c
src/types.h

[BUGFIX] Outname fix

---

src/tracer.c

saves us a lot of unnecessary "find" calls

[IMPROVEMENT] handle_syscall now takes PROCESS_INFO instead of pid

---

src/tracer.c

Note to self: never use github's merge tool ever again, test properly locally

[BUGFIX] error on merge, now properly provides outname to record functions

---

src/record.c

[BUGFIX] Now tests properly for access mode.

---

src/record.c
src/record.h
src/tracer.c

[CORE] Now traces process creation

---

src/record.c
src/record.h
src/tracer.c
src/types.h

Store and record both (potentially) relative and absolute path.

Store both absolute and relative path.

---

src/tracer.c

[BUGFIX] Now stores absolute path names instead of relative ones

---

src/record.c
src/record.h
src/tracer.c
src/types.h

[CORE] File usage recycling implemented, File entries are now stored in a global array.

---

src/record.c
src/record.h
src/tracer.c
src/types.h

Closes #104. Closes #38 
Keep in mind that it's a fork of #94 merged with #109 and modified.

[CORE] Implement rename tracing.

---

src/record.c
src/record.h
src/tracer.c

[CORE] Now tracks executables too

---

.gitignore

add indent files to gitignore, as well as vim .swp files and Ctags

[IMPROVEMENT] improve .gitignore

---

src/tracer.c

[BUGFIX] Now finds executables in PATH as well, also traces first first executable

---

src/tracer.c

[BUGFIX] Fix on bug $1

---

src/hash.c
src/record.c

- Frees allocated memory.
Fixes #172

freeing memory

---

README.md

Add a short description as well as build instructions in repo's README.md

---

man/build-recorder.1

Added manpage for build-recorder.

---

doc/build-recorder-schema.ttl

Provides a schema for the generated RDF.

---

Makefile.am
configure.ac
examples/Makefile.am

- Converts the examples Makefile to automake

Examples under automake

---

Makefile.am
benchmark/Makefile.am
configure.ac

Adds first pass on benchmarking

First pass on benchmarking

---

benchmark/Makefile.am
benchmark/benchmark.awk
configure.ac

Closes #186
Should the print format be pretty? Like, add a table, align them, etc.
Probably I guess.

Add benchmark mechanism. Not pretty, for now.

---

Makefile.am
configure.ac
doc/build-recorder-schema.ttl
src/Makefile.am
src/record.c

Output now contains the RDF schema
side changes:
- Makefile moved to src directory
- RDF base URI changed
Fixes #197

Include schema in output

---

configure.ac

Release 1.0
