eellak/build-recorder

src/algorithms.c
src/algorithms.h
src/main.c
src/tracer.c
src/tracer.h

- Use single-line SPDX license tag instead of text
- Fix copyright attribution by deleting "current"
Fixes #5
Signed-off-by: Alexios Zavras <github@zvr.gr>

Use SPDX license tags

---

src/tracer.h

Header was useless ever since storage specifiers commit

removed useless header

---

src/tracer.c

Got rid of the static buffer and now instead using the dynamic vector. As a result the program consumes less memory and actually has no limit to how big the path string can be.

Store path strings in vector

---

.indent.pro

by default indent will line up identifiers, would prefer if they were placed in the first available position instead

identifier declarations

---

doc/output.md
src/record.c
src/record.h
src/types.h

- openat(2) now handled properly
- autoconf now links with libcrypto
- requested changes
- indent
- added autoconf checks
- headers now in a single lexicographical ordered list
- removed open_files, now each file with a file descriptor "fd" is placed at finfo[fd] array index
- indent
- fixed bug where ARM autoconf wouldn't accept multiline checks without m4_normalize
- Add first pass of description of output format
- Fix missing include for uint8_t type
- Add another missing header (for ptrace_syscall_info)
- Add prototypes of recording functions

RDF first steps

---

src/tracer.c

no longer throws an error when more than 1024 files are open.

There is no longer a 1024 open files limit

---

src/tracer.c

`creat(2)` was treated as if the second argument was the flags, but that wasn't the case. It's now properly handled the way the manual describes.

Creat wrong flags

---

src/hash.c
src/hash.h
src/record.c
src/record.h
src/tracer.c
src/types.h

- openat(2) now handled properly
- autoconf now links with libcrypto
- requested changes
- indent
- added autoconf checks
- headers now in a single lexicographical ordered list
- removed open_files, now each file with a file descriptor "fd" is placed at finfo[fd] array index
- indent
- fixed bug where ARM autoconf wouldn't accept multiline checks without m4_normalize
- Add first pass of description of output format
- Fix missing include for uint8_t type
- Add another missing header (for ptrace_syscall_info)
- Add prototypes of recording functions
- we shouldn't rely on include order, that's a recipe for disaster
- Instead of having 3 parameters, take a convenient FILE_INFO structure. More readable, better performance(we don't need to copy)
- now includes sys/types.h instead of types.h
- …

hash update

---

src/tracer.c

Now ignores `FILE_INFO`s that aren't associated with any traced opened file. Closes #47

Handle null paths

---

configure.ac
src/main.c
src/tracer.c

Initial demo to trace process start and command. Closes #56 if and only if we go after the `cmdline` solution mentioned in that issue.

Trace pstart

---

src/tracer.c

Yet another silly bug, global variables deserve the hate. Closes #87

[BUGFIX] Now properly uses "pi" instead of global variable "pinfo"

---

src/tracer.c

Found a bug while trying to compile the [xbps package manager](https://github.com/void-linux/xbps). Turns out `next_pinfo` was buggy.

[BUGFIX] Out of bounds access Segfault fix

---

src/tracer.c

Previously we would just `strdup(3)` absolute paths in `absolutepath(3)`, this proved to be incorrect since "unreal" paths(such as `/usr/bin/../lib`) would falsely be duplicated and marked as absolute paths. Now properly uses `realpath(3)` in that scenario as well.

[BUGFIX] Now properly finds the realpath of absolute paths

---

src/record.c
src/record.h
src/tracer.c
src/types.h

Huge changes in this pull request.
A scenario which has been troubling me for quite some time now, handlers who run during `syscall_entry` instead of `syscall_stop`.
To implement the tracing of `rename(2)` calls i once again needed that feature. This time instead of hacking my way around it i decided to tackle it with a demo solution.
That is:
Said function has the same structure the original `handle_syscall(3)` had and is meant to run computations that we can't run after the system call has returned(that is, on `PTRACE_SYSCALL_INFO_EXIT`). A new entry has been introduced in `PROCESS_INFO` to hold the result of the former function's computations, namely `PROCESS_INFO::entry_info`.
Original `handle_syscall(3)` has been renamed to `handle_syscall_exit(3)`.
A demo for `record_rename` has …

[CORE] implemented rename tracing, record format demo, code structure changed

---

src/tracer.c
src/types.h

Debugging these last few weeks i slowly came to the realization that the way we had our `finfo` and `pinfo` collections organized was wrong.
A simple explanation of what was going on up until now would be:
We had a global `finfo` array
We had a global `pinfo` array
Each `pinfo` had an internal array which would hold indexes pointing at the global `finfo` array's elements
Upon a file encounter on a process `pid` with the file's `id = fd`:
1. Search the global `finfo` array to see if the file was ever seen before
2. If not, add it
3. have the corresponding `pinfo`'s array element at index `fd` point to the index of the previously existing or newly defined file at the global `finfo` array.
Later we found out that we need to skip files opened for writing during our `1.` search phase. That's …

[IMPROVEMENT] Superior data design.

---

src/tracer.c
src/types.h

`pinfo` array has been re-organized to maximize cache-hits when searching using `find_pinfo(3)`. Processes that end are now removed from the array as discussed in #131 .

[IMPROVEMENT] Data oriented design and optimizations

---

.indent.pro
Makefile.am
src/hash.c
src/hash.h
src/hashmap.c
src/hashmap.h
src/tracer.c
src/types.h

I implemented a simple hashmap that resolves conflicts using open addressing linear probing. Using the first string hashing algorithm I found! I used `&` to bound the output using power of two sizes for the underlying array.
I didn't make any attempts to make the interface generic other than using `typedef`s here and there.
While it is a "naive" hashtable(If i ever was to optimize it I'd using something better than a plain `&` and probably a robinhood hashing instead) running the tests yields adequate results, in fact the complexity no longer scales with array size! With `hashmap_insert(3)`(the one and only function i needed to implement) taking up only 0.02% of the total runtime(previously it could be as high as 10% given a "big" build, for example, the linux kernel with all config …

[IMPROVEMENT] Hashmap implementation! Bigger builds are now faster!

---

src/tracer.c

There was a bug there that was just too rare to occur. If for any reason two files shared a name, but the first one was a regular file and the second was a folder a segfault would pop up since we would `strcmp(NULL, NOT_NULL)` or vice-versa.

[BUGFIX] Checks for null before comparing.

---

.indent.pro
configure.ac
src/hash.c
src/tracer.c

- openat(2) now handled properly
- autoconf now links with libcrypto
- requested changes
- indent
- added autoconf checks
- headers now in a single lexicographical ordered list
- removed open_files, now each file with a file descriptor "fd" is placed at finfo[fd] array index
- indent
- fixed bug where ARM autoconf wouldn't accept multiline checks without m4_normalize
- Add first pass of description of output format
- Fix missing include for uint8_t type
- Add another missing header (for ptrace_syscall_info)
- Add prototypes of recording functions
- we shouldn't rely on include order, that's a recipe for disaster
- Instead of having 3 parameters, take a convenient FILE_INFO structure. More readable, better performance(we don't need to copy)
- now includes sys/types.h instead of types.h
- …

Update hashing code

---

configure.ac
src/tracer.c

as it turns out they are not present in all linux distributions.
Added macro checks for those scenarios, one being when building build-recorder on a raspberry pi running raspberry pi OS.
Closes #149

Added configure.ac checks for all syscall constants of type SYS_syscall

---

benchmark/Makefile.am
examples/Makefile.am

Makes examples and benchmark non-default rules.
Since these directories are now included in the recursive top-level make, they should not be performed on the target `all`.
Fixes #194

Not making examples and benchmark by default

---

benchmark/Makefile.am
configure.ac

- fixes typo (PROG instead of PROGS)
- uses full path for time
closes #198
closes #199

fix autoconf

---

src/Makefile.am

Fixed an issue where headers and schema needed to build build-recorder were not included in the generated tarball after running 'make dist'.
